Repository Plutonomicon/cardano-transaction-lib, pull requests merged in 2022-06, with the labels that each got.

#476 Fix unpackMintAssets (FFI)
  src/Cardano/Types/Value.purs
  src/Deserialization/Transaction.purs
  src/Metadata/FromMetadata.purs
  src/Metadata/Seabug/Share.purs
  src/Types/Int.purs
Labels: bug, critical

#487 Fix applyArgs decoding issue
  src/QueryM.purs
Labels: bug

#568 Fix `mustBeSignedBy`
  CHANGELOG.md
  package-lock.json
  package.json
  src/Types/ScriptLookups.purs
Labels: bug, critical, backport

#595 Rename `require` function to not cause problems with webpack
  CHANGELOG.md
  src/Types/ScriptLookups.purs
Labels: backport

#611 Fix utxo min-ada-value calculation
  CHANGELOG.md
  src/BalanceTx.purs
  src/Constants/Alonzo.purs
  src/Contract/Monad.purs
  src/Contract/ProtocolParameters/Alonzo.purs
  src/QueryM.purs
  src/QueryM/ProtocolParameters.purs
Labels: bug, backport
